import type { ContentItem } from "@/lib/store";

/**
 * Design sources extracted from user's browser bookmarks (2026-04-13).
 * Organized by the bookmark folder structure.
 */

export const BOOKMARK_SOURCES: ContentItem[] = [
  // ── Typography ──
  {
    id: "bk-type-is-beautiful",
    title: "Type is Beautiful",
    description: "The leading Chinese-language publication on typography and visual culture. Bridging Western typographic tradition with CJK design discourse.",
    imageUrl: "https://images.unsplash.com/photo-1455659817273-f96807779a8a?w=600",
    category: "graphic_design",
    tags: ["typography", "chinese", "editorial", "publication"],
    mediaType: "image",
    sourceUrl: "http://www.typeisbeautiful.com/",
  },
  {
    id: "bk-grilli-type",
    title: "Grilli Type",
    description: "Independent Swiss type foundry crafting distinctive typefaces that push the boundaries of contemporary typography. Home of GT America, GT Walsheim, and GT Sectra.",
    imageUrl: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600",
    category: "graphic_design",
    tags: ["typography", "swiss", "type foundry", "typeface"],
    mediaType: "image",
    sourceUrl: "https://www.grillitype.com/",
  },
  {
    id: "bk-fonts-in-use",
    title: "Fonts In Use",
    description: "A curated archive documenting typography in real-world use — from signage to book covers to packaging. The definitive field guide to how type lives in the world.",
    imageUrl: "https://images.unsplash.com/photo-1455659817273-f96807779a8a?w=600",
    category: "graphic_design",
    tags: ["typography", "archive", "reference", "type specimen"],
    mediaType: "image",
    sourceUrl: "https://fontsinuse.com/",
  },
  {
    id: "bk-typewolf",
    title: "Typewolf",
    description: "Curated guide to the best fonts and typography on the web. Jeremiah Shoaf's meticulous eye identifies trending typefaces and pairing recommendations.",
    imageUrl: "https://images.unsplash.com/photo-1455659817273-f96807779a8a?w=600",
    category: "graphic_design",
    tags: ["typography", "web fonts", "curation", "guide"],
    mediaType: "image",
    sourceUrl: "https://www.typewolf.com/guides",
  },
  {
    id: "bk-pangram-pangram",
    title: "Pangram Pangram Foundry",
    description: "Contemporary type foundry known for distinctive, high-quality typefaces with generous licensing. Known for Neue Montreal, Right Grotesk, and Editorial New.",
    imageUrl: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600",
    category: "graphic_design",
    tags: ["typography", "type foundry", "contemporary", "licensing"],
    mediaType: "image",
    sourceUrl: "https://pangrampangram.com/collections/fonts",
  },
  // ── Studios: China ──
  {
    id: "bk-a-black-cover",
    title: "A Black Cover Design",
    description: "Shanghai-based graphic design studio led by Guang Yu, known for bold experimental work bridging Eastern and Western visual languages. Award-winning book and identity design.",
    imageUrl: "https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=600",
    category: "graphic_design",
    tags: ["studio", "shanghai", "chinese", "book design", "experimental"],
    mediaType: "image",
    sourceUrl: "https://ablackcover.com/",
  },
  {
    id: "bk-702-design",
    title: "702 Design",
    description: "Chinese graphic design studio producing refined visual identity and editorial work with a distinctly contemporary East Asian sensibility.",
    imageUrl: "https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=600",
    category: "graphic_design",
    tags: ["studio", "chinese", "identity", "editorial"],
    mediaType: "image",
    sourceUrl: "http://www.by702.com/",
  },
  {
    id: "bk-kongsi",
    title: "Kongsi Design 共 一 亻一 半",
    description: "Chinese design collective exploring the intersection of traditional Chinese culture with contemporary visual communication.",
    imageUrl: "https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=600",
    category: "graphic_design",
    tags: ["studio", "chinese", "cultural", "contemporary"],
    mediaType: "image",
    sourceUrl: "https://kongsidesign.com/HOME",
  },
  {
    id: "bk-by-enjoy",
    title: "BY-ENJOY 不亦乐乎",
    description: "Chinese creative studio whose name references Confucian philosophy. Known for a playful yet rigorous approach to design across cultural projects.",
    imageUrl: "https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=600",
    category: "graphic_design",
    tags: ["studio", "chinese", "cultural", "playful"],
    mediaType: "image",
    sourceUrl: "https://by-enjoy.com/work",
  },
  // ── Studios: International ──
  {
    id: "bk-stockholm-design-lab",
    title: "Stockholm Design Lab",
    description: "Swedish design studio renowned for systematic, long-lasting identity systems. Their work for SAS, Ericsson, and the Nobel Prize epitomizes Scandinavian clarity.",
    imageUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=600",
    category: "graphic_design",
    tags: ["studio", "swedish", "identity", "scandinavian", "systematic"],
    mediaType: "image",
    sourceUrl: "https://www.stockholmdesignlab.se/",
  },
  {
    id: "bk-neubau-berlin",
    title: "Neubau Berlin",
    description: "German design studio by Stefan Gandl producing meticulous data-driven typefaces and graphic systems. Their NB International and NB Grotesk are typographic landmarks.",
    imageUrl: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600",
    category: "graphic_design",
    tags: ["studio", "german", "typeface", "data-driven", "systematic"],
    mediaType: "image",
    sourceUrl: "https://neubauberlin.com/studio/",
  },
  {
    id: "bk-studio-fnt",
    title: "Studio fnt",
    description: "Seoul-based graphic design studio by Jaemin Lee, known for poetic, typographically-rich work that bridges Korean and international design cultures.",
    imageUrl: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600",
    category: "graphic_design",
    tags: ["studio", "korean", "typography", "cultural"],
    mediaType: "image",
    sourceUrl: "https://studiofnt.com/",
  },
  {
    id: "bk-sulki-min",
    title: "Sulki & Min (+.+) & <*_*>",
    description: "Seoul-based design duo Sulki Choi and Min Choi, whose cerebral, conceptual poster and book work has redefined Korean graphic design. Teaching at KAIST.",
    imageUrl: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600",
    category: "graphic_design",
    tags: ["studio", "korean", "poster", "conceptual", "academic"],
    mediaType: "image",
    sourceUrl: "https://www.sulki-min.com/wp/category/outcome/poster/",
  },
  {
    id: "bk-dfy-korea",
    title: "DFY Korea",
    description: "South Korean design studio creating refined brand identities and spatial design. Their work balances Korean aesthetic tradition with global design standards.",
    imageUrl: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600",
    category: "graphic_design",
    tags: ["studio", "korean", "branding", "spatial"],
    mediaType: "image",
    sourceUrl: "https://www.dfy.co.kr/about",
  },
  {
    id: "bk-plus-ex",
    title: "Plus X Creative Partner",
    description: "South Korean UX and brand design studio known for cohesive digital-physical brand experiences. Major Korean tech and consumer brand work.",
    imageUrl: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600",
    category: "graphic_design",
    tags: ["studio", "korean", "ux", "branding", "digital"],
    mediaType: "image",
    sourceUrl: "https://www.plus-ex.com/",
  },
  // ── Graphic: Poster Archives ──
  {
    id: "bk-another-graphic",
    title: "Another Graphic",
    description: "Archive of contemporary graphic design focused on typographic treatment. A curated collection documenting how designers use type as the primary visual element.",
    imageUrl: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600",
    category: "graphic_design",
    tags: ["archive", "poster", "typography", "contemporary"],
    mediaType: "image",
    sourceUrl: "https://anothergraphic.org/",
  },
  {
    id: "bk-trend-list",
    title: "Trend List",
    description: "Documenting visual trends in graphic design since 2011. An invaluable archive tracking how aesthetic movements emerge, peak, and evolve in poster and print design.",
    imageUrl: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600",
    category: "graphic_design",
    tags: ["archive", "trends", "poster", "documentation"],
    mediaType: "image",
    sourceUrl: "https://trendlist.org/",
  },
  {
    id: "bk-typographic-posters",
    title: "Typo/Graphic Posters",
    description: "Curated collection of typographic posters from around the world. Celebrating the art of combining type, image, and message into single powerful compositions.",
    imageUrl: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600",
    category: "graphic_design",
    tags: ["archive", "poster", "typography", "international"],
    mediaType: "image",
    sourceUrl: "https://www.typographicposters.com/",
  },
  // ── Awards & Institutions ──
  {
    id: "bk-agi",
    title: "AGI — Alliance Graphique Internationale",
    description: "The most exclusive international graphic design organization, with invitation-only membership limited to approximately 500 of the world's most distinguished designers.",
    imageUrl: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600",
    category: "graphic_design",
    tags: ["institution", "international", "elite", "graphic design"],
    mediaType: "image",
    sourceUrl: "https://a-g-i.org/work/",
  },
  {
    id: "bk-dandad",
    title: "D&AD Awards",
    description: "Global advertising, design, and digital awards known for their legendary difficulty. A Yellow Pencil is considered the highest honor in commercial creativity.",
    imageUrl: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600",
    category: "graphic_design",
    tags: ["awards", "international", "advertising", "design"],
    mediaType: "image",
    sourceUrl: "https://www.dandad.org/en/d-ad-awards/",
  },
  {
    id: "bk-archives-design",
    title: "archives.design",
    description: "Digital archive preserving the history of graphic design through a curated timeline of significant works, movements, and practitioners from the 20th century forward.",
    imageUrl: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600",
    category: "graphic_design",
    tags: ["archive", "history", "digital", "timeline"],
    mediaType: "image",
    sourceUrl: "https://archives.design/",
  },
  {
    id: "bk-stiftung-buchkunst",
    title: "Stiftung Buchkunst — Best Book Design",
    description: "The German Book Art Foundation's annual competition recognizing the world's most beautifully designed books. The gold standard for book design excellence since 1966.",
    imageUrl: "https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=600",
    category: "book_design",
    tags: ["awards", "book design", "german", "international"],
    mediaType: "image",
    sourceUrl: "https://www.stiftung-buchkunst.de/en/best-book-design-from-all-over-the-world/the-awardees/",
  },
  // ── Book Shops (Japan) ──
  {
    id: "bk-fragile-books",
    title: "FRAGILE BOOKS",
    description: "Japanese bookshop specializing in art, design, and photography books. A pilgrimage destination for collectors of rare design monographs and exhibition catalogs.",
    imageUrl: "https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=600",
    category: "book_design",
    tags: ["bookshop", "japanese", "art books", "rare books"],
    mediaType: "image",
    sourceUrl: "https://www.fragile-books.com/",
  },
  {
    id: "bk-book-and-sons",
    title: "BOOK AND SONS",
    description: "Tokyo bookshop dedicated to graphic design publications. Their curated selection spans Japanese and international design monographs, from Sugiura Kohei to Swiss modernism.",
    imageUrl: "https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=600",
    category: "book_design",
    tags: ["bookshop", "japanese", "graphic design", "tokyo"],
    mediaType: "image",
    sourceUrl: "https://store.bookandsons.com/",
  },
  {
    id: "bk-natsume-books",
    title: "Natsume Books 夏目書房",
    description: "Jimbocho antiquarian bookshop in Tokyo's legendary book district, specializing in rare art and design books. A treasure trove for vintage Japanese design publications.",
    imageUrl: "https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=600",
    category: "book_design",
    tags: ["bookshop", "japanese", "antiquarian", "jimbocho", "rare books"],
    mediaType: "image",
    sourceUrl: "https://www.natsume-books.com/",
  },
  {
    id: "bk-nostos-books",
    title: "nostos books ノストスブックス",
    description: "Tokyo bookshop buying and selling design, craft, and art books. A carefully curated space where every shelf tells a story about visual culture.",
    imageUrl: "https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=600",
    category: "book_design",
    tags: ["bookshop", "japanese", "craft", "art books"],
    mediaType: "image",
    sourceUrl: "https://nostos.jp/",
  },
  {
    id: "bk-komiyama-tokyo",
    title: "Komiyama Tokyo 小宮山書店",
    description: "Jimbocho antiquarian dealing in fine art, photography, and design books. Their Kamekura Yusaku and Yokoo Tadanori collections are legendary among collectors.",
    imageUrl: "https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=600",
    category: "book_design",
    tags: ["bookshop", "japanese", "jimbocho", "kamekura", "yokoo"],
    mediaType: "image",
    sourceUrl: "https://www.book-komiyama.co.jp/",
  },
  {
    id: "bk-seikousha",
    title: "Seikousha 誠光社",
    description: "Independent Kyoto bookshop with a discerning selection of design, literature, and culture titles. A quiet refuge for readers who treat books as aesthetic objects.",
    imageUrl: "https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=600",
    category: "book_design",
    tags: ["bookshop", "japanese", "kyoto", "independent"],
    mediaType: "image",
    sourceUrl: "https://seikosha.stores.jp/",
  },
  // ── Design Inspiration ──
  {
    id: "bk-silencio",
    title: "SILENCIO — Visual Languages",
    description: "Visual design studio exploring the boundary between graphic design and art. Their work speaks through restraint, using silence as a design principle.",
    imageUrl: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?w=600",
    category: "graphic_design",
    tags: ["studio", "visual language", "restraint", "art"],
    mediaType: "image",
    sourceUrl: "https://silencio.es/",
  },
  {
    id: "bk-museum-gestaltung",
    title: "Museum für Gestaltung Zürich",
    description: "Switzerland's premier design museum in Zurich, home to one of the world's most important collections of Swiss graphic design, poster art, and applied arts.",
    imageUrl: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600",
    category: "graphic_design",
    tags: ["museum", "swiss", "zurich", "poster", "collection"],
    mediaType: "image",
    sourceUrl: "https://museum-gestaltung.ch/",
  },
  // ── Designer Portfolios ──
  {
    id: "bk-pentagram-bierut",
    title: "Michael Bierut — Pentagram",
    description: "Pentagram partner whose witty, intellectual approach to identity design has shaped some of America's most recognized brands. Yale School of Art senior critic.",
    imageUrl: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600",
    category: "graphic_design",
    creator: "Michael Bierut",
    tags: ["designer", "pentagram", "identity", "american"],
    mediaType: "image",
    sourceUrl: "https://www.pentagram.com/about/michael-bierut",
  },
  {
    id: "bk-pan-yanrong",
    title: "Pan Yanrong 潘焰荣 — T-CHANGE DESIGN",
    description: "Chinese book designer Pan Yanrong, whose T-CHANGE DESIGN studio produces some of the most refined book design emerging from China today.",
    imageUrl: "https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=600",
    category: "book_design",
    creator: "Pan Yanrong 潘焰荣",
    tags: ["designer", "chinese", "book design", "contemporary"],
    mediaType: "image",
    sourceUrl: "https://www.t-changedesign.com/",
  },
  // ── Web Design / Interaction ──
  {
    id: "bk-seesaw",
    title: "seesaw",
    description: "Curated gallery of the finest web design. A daily dose of digital inspiration, documenting how the web's visual language evolves.",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600",
    category: "graphic_design",
    tags: ["web design", "gallery", "digital", "curation"],
    mediaType: "image",
    sourceUrl: "https://www.seesaw.website/",
  },
  {
    id: "bk-godly",
    title: "Godly",
    description: "Curated gallery of the world's best web design. Features breakdown analysis of standout websites, focusing on interaction, animation, and visual storytelling.",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600",
    category: "graphic_design",
    tags: ["web design", "gallery", "interaction", "animation"],
    mediaType: "image",
    sourceUrl: "https://godly.website/",
  },
  {
    id: "bk-design-reviewed",
    title: "Design Reviewed",
    description: "Archive of historical design artefacts — magazine covers, packaging, advertisements — meticulously catalogued. A visual history of 20th-century commercial design.",
    imageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600",
    category: "graphic_design",
    tags: ["archive", "historical", "magazine", "packaging", "advertising"],
    mediaType: "image",
    sourceUrl: "https://designreviewed.com/",
  },
];
